### ISSUE TITLE
Too long Error message

### ISSUE THREAD

**Issue by oberer-Twix** [project-team-syp2021-22/felerfrei-frontend#31]
Bei der Signup-Page wird der Error nicht korrekt angezeigt, wenn man ein schlechtes Passwort wählt
![Screenshot 2022-04-08 155900](https://user-images.githubusercontent.com/90768661/162451032-56c934c5-fdd1-457d-8244-725480cbb6da.png)

**Comment by robertexplodes** [comment]
resolved with pull reuqest #38
